apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-machineconfigpool
  labels:
    env: rnd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    helm:
      chart: machineconfigpool
      version: 1.0.0
      subPath: helm-openshift-machineconfigpool
    values:
      - env/rnd/values.yaml
    repoURL: https://github.com/my-org/my-repo.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  helm:
    releaseName: custom-machineconfigpool-rnd