machineConfigPools:
  - name: custom
    machineRoles:
      - worker
      - custom
    nodeSelector:
      key: node-role.kubernetes.io/custom
      value: custom1
    paused: false
  - name: infra
    machineRoles:
      - worker
      - infra
    nodeSelector:
      key: node-role.kubernetes.io/infra
      value: ""
    paused: true
  - name: workers
    machineRoles:
      - worker
      - storage
    maxUnavailable: 1
    nodeSelector:
      key: node-role.kubernetes.io/worker
      value: "true"
