{{- range .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: {{ .mcpName }}
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: {{ .machineRoles | toJson }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- else }}
  maxUnavailable: null
  {{- end }}
  nodeSelector:
    matchLabels:
      {{- if .nodeSelector }}
      {{ .nodeSelector.key }}: "{{ .nodeSelector.value }}"
      {{- end }}
  paused: {{ .paused | default false }}
---
{{- end }}
