{{/* Define anchor aliases for commonly-used MCP fields */}}
{{- define "mcpDefaults" -}}
  &mcpDefaults
  maxUnavailable: null
  paused: false
  nodeSelector: {}
{{- end -}}

{{- define "mcpName" -}}
  {{ .Values.mcpName }}
{{- end -}}

{{- define "machineRoles" -}}
  {{ .Values.machineRoles }}
{{- end -}}

{{/* Use anchor aliases for each MCP configuration */}}
{{- range $index, $element := .Values.machineConfigPools }}
{{- $mcpConfig := dict "mcpName" $element.mcpName "machineRoles" $element.machineRoles }}
{{- $mcpConfig := merge $mcpConfig (include "mcpDefaults") }}
{{- $mcpConfig := merge $mcpConfig $element | default (dict) }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: {{ template "mcpName" $mcpConfig }}
spec:
  machineConfigSelector:
    matchExpressions:
      - { key: machineconfiguration.openshift.io/role, operator: In, values: {{ template "machineRoles" $mcpConfig | toYaml | nindent 6 }} }
  {{- if ne $mcpConfig.maxUnavailable nil }}
  maxUnavailable: {{ $mcpConfig.maxUnavailable }}
  {{- end }}
  nodeSelector:
    matchLabels:
      {{- $selector := $mcpConfig.nodeSelector }}
      {{- if not (lookup "v1" "Node" "metadata" "labels" $selector.key) }}
      {{- fail (printf "Node label %q not found" $selector.key) }}
      {{- end }}
      {{ $selector | toYaml | nindent 6 }}
  paused: {{ $mcpConfig.paused }}
{{- end }}

