{{- range .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: {{ .mcpName }}
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: {{ .machineRoles | toJson }}
  maxUnavailable: {{ .maxUnavailable | default 1 }}
  nodeSelector:
    {{- if not .nodeSelector }}
    {{- fail "nodeSelector is required for all MachineConfigPools" }}
    {{- end }}
    matchLabels:
      {{ .nodeSelector.key }}: "{{ .nodeSelector.value }}"
  paused: {{ .paused | default false }}
---
{{- end }}