machineConfigPools:
  - mcpName: infra
    machineRoles:
      - worker
      - infra
    nodeSelector:
      key: node-role.kubernetes.io/infra
      value: ""
    paused: true
  - mcpName: app
    machineRoles:
      - worker
      - app
    maxUnavailable: 1
    nodeSelector:
      key: node-role.kubernetes.io/app
      value: "true"

